export const Faculdade = [
  "AESGA",
  "AESO",
  "ASCES",
  "CPM",
  "ESEF UPE",
  "ESTÁCIO",
  "ESUDA",
  "ETEPLAP",
  "FACET",
  "FACHO",
  "FACHUCA",
  "FACIPE",
  "FACJU",
  "FACOL",
  "FACULDADE SANTA HELENA (FSH)",
  "FACULDADE SANTA MARIA (FSM)",
  "FAFIRE",
  "FAINTVISA",
  "FBV",
  "FG",
  "FJN",
  "FJN PAULISTA",
  "FOCCA",
  "FOP",
  "FOR",
  "FPS",
  "IBGM UNIBRA",
  "IBGM/FG",
  "IPESO",
  "METROPOLITANA",
  "SOPECE",
  "UFPE",
  "UFPE - CAV",
  "UFRPE",
  "UNIBRA",
  "UNICAP",
  "UNIFAVIP",
  "UNIFG",
  "UNINASSAU (FMN)",
  "UNISÃO MIGUEL",
  "UNIVERSO",
  "UPE",
  "UNINABUCO",
  "COLÉGIO PONTUAL",
];

export const Cursos = [
  "ADM & CONTÁBEIS",
  "ADM & REDES",
  "ADMINISTRAÇÃO",
  "CIÊNCIAS CONTÁBEIS",
  "COMUNICAÇÃO SOCIAL",
  "DIREITO",
  "ED. FÍSICA",
  "ENF E FISIO",
  "ENFERMAGEM",
  "ENG. CIVIL",
  "ENG. PROD . CIV.",
  "ENG. PRODUÇÃO",
  "ENGENHARIA",
  "FARMACIA",
  "FISIOTERAPIA",
  "LOGISTICA",
  "MEDICINA",
  "NUTRIÇÃO",
  "ODONTOLOGIA",
  "PSICOLOGIA",
  "PUBLICIDADE",
  "RECURSOS HUMANOS",
  "REDES",
  "RH E LOGISTICA",
  "SERVIÇO SOCIAL",
  "UNIFICADA",
  "MED. VETERINÁRIA",
  "ENG. PROD",
  "ODONTO / ENFERMAGEM",
  "MBA GESTAO DE PESSOAS",
  "COLÉGIO PONTUAL",
];

export const Eventos = [
  "AULA",
  "BAILE",
  "COLA - BAILE",
  "COLA - CULTO",
  "COLAÇÃO",
  "COLAÇÃO - JANTAR",
  "COLAÇÃO UNIFICADA",
  "CULTO",
  "FESTA",
  "FESTA A FANTASIA",
  "FOTO GERAL",
  "FOTO PRAIA",
  "JANTAR DOS PAIS",
  "ENTREGA DE MATERIAL",
  "JANTAR",
  "NOITE DE AUTOGRAFOS",
];

export const Local = [
  "A CONFIRMAR",
  "AGENTINO",
  "AKROPOLIS",
  "ALDEIA",
  "ALDEIA KM 5",
  "AMAZEM 10",
  "ANDREA GUERA",
  "ANFITEATRO",
  "ANFITEATRO - FAINTVISA",
  "ANTURIUS",
  "APENAS STUDIOS",
  "APIPUCOS",
  "ÁRCADIA",
  "ARCADIA APIPUCOS ",
  "ARCADIA BOA VIAGEM",
  "ARCÁDIA PAÇO",
  "ARMAZEM 10 PAULISTA",
  "AUD CTG UFPE",
  "AUD. TABOCAS",
  "AUDITÓRIO",
  "AUDITORIO FJN",
  "AUDITORIO CCSA",
  "AUDITORIO DA UFPE",
  "AUDITORIO DOS MEDICOS",
  "AUDITÓRIO ESTÁCIO",
  "AUDITORIO FBV",
  "AUDITORIO FG",
  "AUDITORIO NASSAU",
  "AV JOÃO DE BARROS",
  "BACUS",
  "BAR 48",
  "BEBERIBE",
  "BELTRÃO",
  "BETH",
  "BLOCO DE DIREITO",
  "BLUE ANGEL ",
  "BOA VIAGEM ",
  "BOI E BRASA CAXANGÁ",
  "CABO",
  "CAMARA DOS VEREADORES",
  "CAMPUS 02",
  "CASA AMARELA",
  "CASA ROSADA",
  "CASTELO EVENTOS",
  "CASTELO PERGENTINO",
  "CCSA",
  "CENTRO DE",
  "CENTRO DE CONVENÇÕES",
  "CHALÉ 2",
  "CLUBE AESGA",
  "CLUBE DOS OFICIAIS",
  "CLUBE UFPE",
  "COCO BAMBU",
  "COLEGIO ETEPLAP",
  "COMBINAR",
  "CONVENÇOES",
  "CPM",
  "CREPERIA ROUGE",
  "DA ASCES",
  "DA FACULDADE",
  "DEISE NOGUEIRA",
  "DI BRANCO",
  "DI BRANCO TORRE",
  "DIFUSORA",
  "DIREITO FJN PAULISTA",
  "EDILSON FRAGA",
  "ESPAÇO FESTAS PIEDADE",
  "ESPAÇO MARIAZINHA",
  "FACOL",
  "FACULDADE",
  "FAFIRE",
  "FLÔL DA FESTA",
  "GRUTA AZUL",
  "GUARARAPES",
  "HABB´S ",
  "HOTEL MANIBU",
  "IMBIRIBEIRA",
  "IMIP",
  "JF RECEPÇÃO CANDEIAS",
  "JOSÉ II",
  "LA FEME",
  "LE PARK",
  "LEDA DOURADO",
  "LOFT",
  "MAÇÃ VERDE",
  "MACHADO",
  "MARCO ZERO",
  "MARIA",
  "MARIA JOSÉ I",
  "MARIA JOSÉ II",
  "MARIA'S",
  "MARIAS RECP",
  "MARIAZINHA ALDEIA",
  "MUSEU DO ESTADO",
  "NA ESUDA",
  "NA FACULDADE",
  "NETO & CIA",
  "NOSSA CASA RECEPÇÕES",
  "OLINDA",
  "PAÇO",
  "PIEDADE",
  "PORTO FINO",
  "PRIVÊ EM PAULISTA",
  "QUADRA ",
  "RENATO ",
  "RENATO MACHADO",
  "RODRIGUES",
  "ROSE",
  "ROSÊ BELTRÃO",
  "SAL E BRASA",
  "SHOPPING",
  "SHOPPING DIFUSORA",
  "SITIO OLHO D`GUA",
  "SOL NASCENTE PISCINA",
  "SPETTUS",
  "SR. REGUEIRA",
  "SUSANA RECEPÇÕES",
  "TABOCAS",
  "TEATRO",
  "TEATRO BEBERIBE",
  "TEATRO DIFUSORA",
  "TEATRO GUARARAPES",
  "TEATRO IMIP",
  "TETRO ",
  "TETRO BEBERIBE",
  "TJ PLENO",
  "UP REÇEPÇÕES",
  "VERDE ESPAÇO ALDEIA",
  "CATARINA LAZER E EVENTOS",
  "NOVILHO GRILL",
];

export const Temporada = [
  "2017.1",
  "2017.2",
  "2018.1",
  "2018.2",
  "2019.1",
  "2019.2",
  "2020.1",
  "2020.2",
  "2021.1",
  "2021.2",
  "2022.1",
  "2022.2",
  "2023.1",
  "2023.2",
  "2024.1",
  "2024.2",
  "2025.1",
  "2025.2",
  "2026.1",
  "2026.2",
  "2027.1",
  "2027.2",
  "2028.1",
  "2028.2",
  "2029.1",
  "2029.2",
  "2030.1",
  "2030.2",
  "2031.1",
  "2031.2",
  "2032.1",
  "2032.2",
  "2033.1",
  "2033.2",
  "2034.1",
  "2034.2",
];

export const Gerente = [
  "GABI",
  "ROGÉRIO",
  "THACIANA",
  "RUTH",
  "BRUNA MARIA",
  "BRUNA ARAUJO",
  "GISELE",
  "MIRIAN",
  "CRISTIANE",
  "JESSICA",
  "AUDREI",
  "ADRIANO",
  "RISOMAR",
];

export const Hd = [
  "HD1",
  "HD2",
  "HD3",
  "HD4",
  "HD5",
  "HD6",
  "HD7",
  "HD8",
  "HD9",
  "HD10",
  "HD11",
  "HD12",
  "HD13",
  "HD14",
  "HD15",
  "HD16",
  "HD17",
  "HD18",
  "HD19",
  "HD20",
  "HD21",
  "HD22",
  "HD23",
  "HD24",
  "HD25",
  "HD26",
  "HD27",
  "HD28",
  "HD29",
  "HD30",
];

const Dados = { Faculdade, Cursos, Eventos, Local, Temporada, Gerente, Hd };
export default Dados;
